export const FETCH_RANDOM_IMAGE = 'FETCH_RANDOM_IMAGE';
export const ADD_IMAGE = 'ADD_IMAGE';
export const START_LOADING = 'START_LOADING';
export const FINISH_LODAING = 'FINISH_LODAING';
export const DELETE_IMAGE = 'DELETE_IMAGE';